### PR TITLE
remove logo from support footer

### PR DESCRIPTION
**Pull request by krbullock**

### CODE REVIEW

**Comment by jonathanstegall** [comment]
I will ask Tanner about this but I'm pretty sure I already did all the footer work and he wants to leave the logo in there.

**Comment by krbullock** [comment]
@jonathanstegall OK sounds good, Bridget seemed to think we'd decided to remove it.

**Comment by jonathanstegall** [comment]
@krbullock yeah, Tanner confirmed.

> Yes, keep the logo, but no form.

**Comment by krbullock** [comment]
OK 👍

**Pull request closed without merging**
